package CalendarioInteractivo;

public class Temas extends javax.swing.JFrame {

    private final MenuPrincipal menuPrincipal;
    
    public Temas(MenuPrincipal menuPrincipal) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.menuPrincipal = menuPrincipal;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tema1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tema2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tema3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tema4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tema5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tema6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tema1.setText("Aplicar");
        tema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema1ActionPerformed(evt);
            }
        });
        jPanel1.add(tema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 70, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema1.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 110));

        tema2.setText("Aplicar");
        tema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema2ActionPerformed(evt);
            }
        });
        jPanel1.add(tema2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 70, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema2.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 260, 110));

        tema3.setText("Aplicar");
        tema3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema3ActionPerformed(evt);
            }
        });
        jPanel1.add(tema3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema3.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 110));

        tema4.setText("Aplicar");
        tema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema4ActionPerformed(evt);
            }
        });
        jPanel1.add(tema4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema4.png"))); // NOI18N
        jLabel10.setText("jLabel1");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 110));

        tema5.setText("Aplicar");
        tema5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema5ActionPerformed(evt);
            }
        });
        jPanel1.add(tema5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 70, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema5.png"))); // NOI18N
        jLabel11.setText("jLabel1");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 100));

        tema6.setText("Aplicar");
        tema6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tema6ActionPerformed(evt);
            }
        });
        jPanel1.add(tema6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 70, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tema6.png"))); // NOI18N
        jLabel12.setText("jLabel1");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 260, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema1ActionPerformed
        menuPrincipal.cambiarTema("tema1.png");  // Cambiar el tema de MenuPrincipal
        menuPrincipal.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_tema1ActionPerformed

    private void tema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema2ActionPerformed
        menuPrincipal.cambiarTema("tema2.jpg");
        this.dispose(); 
        
 
    }//GEN-LAST:event_tema2ActionPerformed

    private void tema3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema3ActionPerformed
        menuPrincipal.cambiarTema("tema3.png");
        this.dispose(); 
    }//GEN-LAST:event_tema3ActionPerformed

    private void tema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema4ActionPerformed
        menuPrincipal.cambiarTema("tema4.png");
        this.dispose();  
    }//GEN-LAST:event_tema4ActionPerformed

    private void tema5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema5ActionPerformed
        menuPrincipal.cambiarTema("tema5.png");
        this.dispose();  
    }//GEN-LAST:event_tema5ActionPerformed

    private void tema6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tema6ActionPerformed
        menuPrincipal.cambiarTema("tema6.png");
        this.dispose();  
    }//GEN-LAST:event_tema6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal menuPrincipal = new MenuPrincipal(); // Crear instancia de MenuPrincipal
                menuPrincipal.setVisible(true); // Mostrar MenuPrincipal
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tema1;
    private javax.swing.JButton tema2;
    private javax.swing.JButton tema3;
    private javax.swing.JButton tema4;
    private javax.swing.JButton tema5;
    private javax.swing.JButton tema6;
    // End of variables declaration//GEN-END:variables
}
